---
# see https://github.com/ansible/team-devtools
_extends: ansible/team-devtools
exclude-contributors:
  - pre-commit-ci
  - renovate
autolabeler:
  - label: skip-changelog
    title:
      - /pre-commit autoupdate/
      - "/^Update .+ (to [v.0-9a-f]+|monorepo \\(.+\\))$/"
      - "/^Replace dependency .+ with .+$/"
    body:
      - "/type: chore/i"
    branch:
      - /^chore/i
  - label: bug
    branch:
      - /^fix/i
    body:
      - "/type: fix/i"
  - label: feature
    title:
      - /^(feat|feature)/i
    body:
      - "/type: feature/i"
  - label: deprecated
    title:
      - /^deprecat(ed|ion)/i
    body:
      - "/type: deprecat(ed|ion)/i"
